Implementierung von Gruppenmanagement
HeroPP/server pull request #9
Opened 2022-09-18 23:48 UTC by joCur

- Gruppen können von jedem erstellt werden
- mit Hilfe eines einladungs codes kann einer Gruppe beigetreten werden
- Gruppen können verlassen werden
- Gruppen können gelöscht werden

- Skills und Abilities hängen nun an der Gruppe, nicht am Owner
- Anpassung und Tests der Controller
- Migration von vorne begonnen, um Fehler im Skript zu unterbinden

2022-09-19 07:06 UTC, JeremySoftware requested changes
Muss im CharacterRepository noch was gemacht werden bezüglich des neuen IUserRepositories vgl. AbilitiyRepository?

2022-09-19 07:06 UTC, JeremySoftware commented on Hero.Server.DataAccess/Repositories/SkillRepository.cs
Da schummelt jemand leerzeichen rein, um sie dann bei mir zu kommentieren ._.

2022-09-19 09:12 UTC, joCur commented on Hero.Server.DataAccess/ModelConfigurations/GroupModelConfiguration.cs
> +                .WithOne()
Richtig, bin noch am überlegeben, ob es anders sinnvoller wäre.

2022-09-19 09:14 UTC, joCur commented on Hero.Server.DataAccess/Repositories/SkillRepository.cs
Verdammt, mein plan ist aufgeflogen

2022-09-19 09:17 UTC, joCur commented
> Muss im CharacterRepository noch was gemacht werden bezüglich des neuen IUserRepositories vgl. AbilitiyRepository?

Ich bin mir nicht sicher, worauf du im Bezug auf das UserRepository hinaus willst? Meinst du weil ich Abilities und Skils in die Gruppe gezogen habe und Charaktere nicht?

2022-09-19 09:20 UTC, JeremySoftware commented
> > Muss im CharacterRepository noch was gemacht werden bezüglich des neuen IUserRepositories vgl. AbilitiyRepository?
> 
> Ich bin mir nicht sicher, worauf du im Bezug auf das UserRepository hinaus willst? Meinst du weil ich Abilities und Skils in die Gruppe gezogen habe und Charaktere nicht?

chso, daran liegt das ^^. Dann müsste das passen. Fürs erste brauch der User ja kein Mitglied mehrerer Gruppen sein. Langfristig könnte es auf jeden Fall sinnvol werden, wenn wir zum Beispiel ein aufwändigeres OneShot oder eine zweite Kampange mit anderem Gamemaster starten wollen, ohne die alte aufzugeben.

2022-09-19 09:22 UTC, joCur commented
> > > Muss im CharacterRepository noch was gemacht werden bezüglich des neuen IUserRepositories vgl. AbilitiyRepository?
> > 
> > 
> > Ich bin mir nicht sicher, worauf du im Bezug auf das UserRepository hinaus willst? Meinst du weil ich Abilities und Skils in die Gruppe gezogen habe und Charaktere nicht?
> 
> chso, daran liegt das ^^. Dann müsste das passen. Fürs erste brauch der User ja kein Mitglied mehrerer Gruppen sein. Langfristig könnte es auf jeden Fall sinnvol werden, wenn wir zum Beispiel ein aufwändigeres OneShot oder eine zweite Kampange mit anderem Gamemaster starten wollen, ohne die alte aufzugeben.

Jap, ich baue es gerade auch so um, dass der Charakter einer Gruppe zugeordnet ist, dass macht es dann einfacher für den Umbau, wenn wir dann mehrere Gruppen wollen.

2022-09-19 10:02 UTC, joCur commented on Hero.Server.DataAccess/Repositories/SkillRepository.cs
weg

2022-09-19 13:26 UTC, JeremySoftware commented on Hero.Server.DataAccess/Repositories/CharacterRepository.cs
> +
Leerzeile 👀

2022-09-19 13:44 UTC, joCur commented on Hero.Server.DataAccess/Repositories/CharacterRepository.cs
> +
das muss so

2022-09-20 06:56 UTC, JeremySoftware approved these changes
Da ist immernoch eine Leerzeile zu viel, aber go for it :D

2022-09-20 19:59 UTC, merged